version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # for external (host) access
      - "29092:29092" # for internal Docker network access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: "-Xms32M -Xmx64M"

  feedlistenerservice:
    build:
      context: .
      dockerfile: src/FeedListenerService/Dockerfile
    container_name: feedlistenerservice
    depends_on:
      - kafka
    environment:
      Kafka__BootstrapServers: kafka:29092
    ports:
      - "5000:80"

  ingestservice:
    build:
      context: .
      dockerfile: src/IngestService/Dockerfile
    container_name: ingestservice
    depends_on:
      - kafka
      - sqlserver
      - redis
      - mongodb
      - elasticsearch 
    environment:
      Kafka__BootstrapServers: kafka:29092
      ConnectionStrings__SqlServer: "Server=sqlserver,1433;Database=Sports365;User Id=sa;Password=Strong!Passw0rd;TrustServerCertificate=True;Encrypt=False;"
      Redis__Connection: "redis:6379"
      MongoDB__Connection: "mongodb://mongodb:27017"
      Elasticsearch__Url: "http://elasticsearch:9200"
    ports:
      - "5001:80"

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Strong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./sqlserver-init:/docker-entrypoint-initdb.d

volumes:
  sqlserver-data:
